import type { Chapter } from "./content-types";

export const moonChapters: Chapter[] = [
  {
    id: "night-went-gray",
    number: 1,
    title: "The Night Went Gray",
    preview: true,
    body: [
      "Once, the town slept under a silver moon.",
      "Then one night, the moon went soft and gray. Bedroom windows glowed, but the sky did not. A child hugged a pillow and whispered,",
      "“Mom… the moon looks tired.”",
      "High on a stone ledge, a tiny firefly named Pip watched the faded sky. Her own glow was only a honey-colored speck.",
      "“If the moon can’t shine,” Pip said, “what chance do I have?”",
      "She lifted off into the dark — one small spark in a big quiet town.",
    ],
  },
  {
    id: "rook-balloon-rocket",
    number: 2,
    title: "Rook and the Balloon Rocket",
    preview: false,
    body: [
      "Clank. String. Scrap metal.",
      "In a junkyard workshop, a raccoon named Rook wrestled a balloon rocket made of patches and hope.",
      "“Almost— whoa!”",
      "The rocket tipped. Pip steadied it with her tiny light.",
      "“Hey,” Rook said. “Tiny flashlight with wings.”",
      "“I’m Pip. The moon forgot how to glow. Kids can’t sleep.”",
      "Rook grinned. “Then we go get it. I’ve got a rocket. You’ve got spark.”",
      "“It’s a small spark,” Pip said.",
      "“Small sparks start big nights,” Rook answered. “Climb in.”",
      "They launched into the gray night.",
    ],
  },
  {
    id: "cloud-maze",
    number: 3,
    title: "The Cloud Maze",
    preview: false,
    body: [
      "Soft blue clouds twisted into a maze. The rocket bumped and spun.",
      "“I can’t see the path!” Rook cried.",
      "Pip flew ahead. Her light painted a golden trail through the fog.",
      "“This way… left… now straight!”",
      "They burst out above the clouds. Pip looked surprised she had led.",
      "“See?” Rook said. “Small light. Big path.”",
    ],
  },
  {
    id: "owl-shine",
    number: 4,
    title: "The Owl Who Kept the Shine",
    preview: false,
    body: [
      "On a cloud nest sat a round Owl, buried in stolen sparkles and stars.",
      "“Mine. All shiny. Mine.”",
      "“We need a little glow for the moon,” Rook said.",
      "“The moon can get a night-light,” the Owl sniffed, “like everyone else.”",
      "Pip’s glow flickered — then steadied.",
      "“Keeping light doesn’t make more light,” she said. “Sharing does.”",
      "She offered one tiny spark. The Owl hesitated… then dropped a single star into her hands.",
      "“…One,” he grumbled. “And bring it back if the moon’s rude.”",
    ],
  },
  {
    id: "dark-luma",
    number: 5,
    title: "Dark Luma",
    preview: false,
    body: [
      "They found Luma, Earth’s moon, sitting on a cloud like a cold stone — charcoal, dim, almost no light at all. One soft tear shone on her cheek.",
      "“Everyone looks up for light,” Luma whispered. “Tonight I have none.”",
      "“Then we’ll fix you,” Pip promised.",
      "Luma stayed dark.",
    ],
  },
  {
    id: "pip-tries",
    number: 6,
    title: "Pip Tries (and Tries)",
    preview: false,
    body: [
      "Pip tried everything she could invent.",
      "She poured star-sparks onto Luma. They fizzled and slid away. “They’re pretty,” Luma said. “They just aren’t mine.”",
      "She polished Luma with a tiny cloth. The cloth turned gray. Luma stayed dark.",
      "She gathered a firefly choir. Together they shone a bright beam. It painted Luma’s surface — but not her heart.",
      "She wrapped Luma in a glow blanket. Luma felt warmer… not brighter.",
      "She bounced Rook’s lantern-light with a shiny lid. The beam died in the dark.",
      "She painted a yellow smile on Luma’s cheek. It dripped into a sad gray smudge.",
      "She and Rook built a spark machine. It coughed gray smoke onto Luma’s nose. “Science is canceled,” Pip said.",
      "She even tried to be the moon herself — glowing as hard as she could. From town, she looked like one more star. Luma stayed a dark shape beside her.",
      "“You’re wonderful,” Luma said. “You’re not me.”",
      "Pip landed, tiny and tired. “Maybe,” she whispered, “I should ask other lights. Lights that already know how to shine.”",
    ],
  },
  {
    id: "other-lights",
    number: 7,
    title: "Advice from Other Lights",
    preview: false,
    body: [
      "Pip asked the lights who already knew how to shine. None of them could fix Luma — but each one tried kindly.",
      "The Lantern said: “Be steady. Shine without flickering.” Pip glowed steady beside Luma. Luma stayed dark. “Steady is good for paths,” Luma murmured. “I am not a path.”",
      "Jack the jack-o’-lantern said: “Carve a funny face! Seasonal shine!” Pip shaped a tiny smile of light. It faded into shadow. “I’m not a pumpkin,” Luma said, almost smiling.",
      "The Candle whispered: “Sometimes you don’t need big light. Just sit close.” Pip sat close and glowed gently. It was cozy. Luma stayed dark. “I feel less alone,” Luma said. “But I still can’t shine.”",
      "Glowcap the mushroom said: “Borrow the forest. Wear our shine.” Pip draped soft mushroom glow over Luma. Beautiful — for a moment. Then it sank into the dark. “Forest light belongs to the forest,” Luma said.",
      "The Streetlight boomed: “SIZE! Cover more ground! Brighter! Bigger!” Pip and Rook blasted every scrap of light toward Luma. The town blinked. Luma stayed a dark stone. “I am not a street,” Luma said quietly. “I am a moon who forgot.”",
      "The Stars chimed: “Come shine with us! Many small lights!” Pip joined them in a glittering net. It was gorgeous. It did not make Luma bright. “Borrowed glitter still isn’t me,” Luma said.",
      "Pip’s glow was thinner than ever. “Every light has an idea,” she whispered. “None of them fix you.”",
      "“Then ask someone bigger,” Rook said gently. “Someone who sees all the lights.”",
    ],
  },
  {
    id: "ask-the-sun",
    number: 8,
    title: "Ask the Sun",
    preview: false,
    body: [
      "“Night’s over,” Rook said. “Our ideas are over.”",
      "“Not over,” Pip said. “Just daytime. Who’s brighter than everyone?”",
      "They flew toward the rising Sun — big, warm, a little too sure of himself.",
      "“Whoa — little spark,” the Sun said. “Careful. I don’t do shade.”",
      "“Please,” Pip said. “Our moon — Luma — went dark. I asked a lantern, a jack-o’-lantern, a candle, a mushroom, a streetlight, the stars… Nothing stuck.”",
      "The Sun was quiet a moment. “Hmm. Moons aren’t my department. I shine. They… borrow.”",
      "“So you don’t have a fix?” Pip asked.",
      "“Not for someone your size,” the Sun said, honest and kind. “Not for someone her kind. But — Mars has two moons. They shine harder than any moons I know. Stubborn little lights. Go ask them.”",
      "“Mars?” Rook gulped. “That’s… a hike.”",
      "“Take the day wind,” the Sun said. “And don’t stare at me too long.”",
      "Pip nodded, scared and brave. “Thank you.”",
    ],
  },
  {
    id: "moons-of-mars",
    number: 9,
    title: "The Moons of Mars",
    preview: false,
    body: [
      "The balloon rocket rattled toward a red world. Two small moons tumbled nearby — Phob (bigger, bold) and Deim (smaller, soft).",
      "“Incoming firefly!” Phob called.",
      "“And a raccoon in a flying trash can,” Deim added. “Cute.”",
      "“I’m Pip,” she said. “Luma — Earth’s moon — lost her glow. The Sun said you shine brighter than any moons. Please… how?”",
      "“We don’t shine instead of Mars,” Phob said.",
      "“We shine with each other,” Deim said. “When one dims, the other stays close. Two small lights. One job.”",
      "“But I’m one light,” Pip said. “Luma’s alone.”",
      "“Then she isn’t fixed by brighter stuff poured on her,” Phob said.",
      "“She’s fixed when someone stays,” Deim said, “and shares a real spark. Not borrowed stars. Not lantern rules. Not streetlight size. Yours.”",
      "“I tried giving her everything else,” Pip whispered.",
      "“Everything else isn’t you,” Phob said.",
      "“Go home,” Deim said. “Sit with her in the dark. Offer the glow you were afraid was too small. That’s the Mars-moon way.”",
      "Pip’s eyes shone. “The failed tries… weren’t wrong,” she said. “They were practice.”",
      "“Then let’s practice being home,” Rook said.",
    ],
  },
  {
    id: "glow-comes-back",
    number: 10,
    title: "The Glow Comes Back",
    preview: false,
    body: [
      "Night again. Luma still dark. The town still waiting.",
      "Pip landed on Luma’s cheek — no jars, no machines, no paint, no borrowed shine.",
      "“I asked the lantern, Jack, the candle, Glowcap, the streetlight, and the stars,” Pip said. “They were kind. They couldn’t fix you. I asked the Sun. He didn’t know. I asked Mars’s moons. They did.”",
      "“What did they say?” Luma asked.",
      "“That small lights fix big dark… together. And that my spark was enough all along.”",
      "Pip pressed her own glow to Luma’s cheek.",
      "Warmth spread — slow, then silver-gold.",
      "Luma brightened.",
      "Windows lit. Children leaned out and cheered. Rook whooped from the balloon. Far below, the lantern flickered proudly, Jack grinned, the candle soft-smiled, Glowcap hummed, the streetlight pretended not to be impressed, and the stars winked like they knew.",
      "“I remember how,” Luma said.",
      "“Because you weren’t alone,” Pip answered.",
      "Far below, a child whispered, “Look! She’s back!”",
      "Pip turned to us, soft as a night-light:",
      "“Even a little light… if you share it… can fill a whole night.”",
    ],
  },
];
