import type { Song } from "./content-types";

export const bananaSongs: Song[] = [
  {
    id: "see-you-next-peel",
    number: 1,
    title: "Peel You Later",
    subtitle: "A hammock goodbye for sleepy peels",
    preview: true,
    lyrics: [
      "Tiny legs, leaf-cape light,",
      "Hammock swinging in the night.",
      "Giggle Jungle humming low—",
      "Friends are snoring in a row.",
      "",
      "Verse",
      "Coconut fell with a soft bonk,",
      "Captain Coco on the cliff.",
      "We don't crack a friend to win.",
      "We sit. We talk. We lift.",
      "",
      "Chorus",
      "When life gets hard as a coconut,",
      "Crack it open with kindness.",
      "Shells can be tough and still be kind.",
      "Softness is not a weakness.",
      "See you next peel, see you next peel,",
      "Cape on the breeze, hearts on the hill.",
      "",
      "Verse — hush",
      "Purple monkeys in a bunk,",
      "Grog's a blanket, warm and wide.",
      "Duke Durian rests his spikes—",
      "Even prickles need a side.",
      "",
      "Final chorus — whisper",
      "When life gets hard as a coconut,",
      "Crack it open with kindness.",
      "See you next peel…",
      "Good night, jungle.",
    ],
    placement: "Chapter 1 closer; soft reprise under every Banana Boy night scene.",
  },
  {
    id: "playtocol",
    number: 2,
    title: "Optional Wiggles",
    subtitle: "The bedtime rule book that learned to giggle",
    preview: false,
    lyrics: [
      "Rows and rules and shiny plans,",
      "Sunglasses on a pineapple stand.",
      "Protocol means stay in line—",
      "Until the jungle asks for time.",
      "",
      "Verse",
      "Tiny steps for tiny legs,",
      "Offbeat coconut percussion.",
      "A little mess is not a mess",
      "If everybody's dancing some.",
      "",
      "Chorus",
      "Playtocol, playtocol,",
      "Safe can still be swingy.",
      "Wiggle optional—then mandatory,",
      "Softly, not too clingy.",
      "Playtocol, playtocol,",
      "Un-laminate the day.",
      "Keep the kindness. Lose the stiffness.",
      "Let the plaza play.",
      "",
      "Bridge",
      "No surprises used to mean no joy.",
      "Now surprises mean a friend.",
      "Best shiny-sunglasses vibe:",
      "A rule that learns to bend.",
      "",
      "Soft reprise",
      "Playtocol…",
      "Wiggle once…",
      "Then rest.",
    ],
    placement: "Chapter 2 (Pineapple Protocol); hum under the plaza dance.",
  },
  {
    id: "red-button-kindness",
    number: 3,
    title: "Sleepy Cup Beeps",
    subtitle: "Whirr-y’s hush-hush smoothie song",
    preview: false,
    lyrics: [
      "Blendy-ready, googly eyes,",
      "Berries in a sleepy cup.",
      "Whirr-y hums a morning tune—",
      "Then the whirl tries to speed up.",
      "",
      "Verse",
      "Too much swirl can steal the sweet.",
      "Too much rush can skip the joke.",
      "Hold the red button, tell a laugh,",
      "Let the smoothie find its folk.",
      "",
      "Chorus",
      "Red button kindness, easy now.",
      "Stay blended with your friends.",
      "Not against them, not too loud—",
      "A swirl that knows when it ends.",
      "Weird is a superfood, it's true.",
      "Party-trainee, beep good night.",
      "",
      "Verse — hush",
      "Leaf blanket over sticky smiles.",
      "Ball-pit monkeys start to snore.",
      "Two blenders hum a harmony",
      "softer than the shack before.",
      "",
      "Final hush",
      "Red button… kindness…",
      "Blend… then rest.",
    ],
    placement: "Chapter 3 (Blender of Doom); closer after the swirl contest.",
  },
  {
    id: "slippery-dance",
    number: 4,
    title: "Pudding Star Shuffle",
    subtitle: "A wobbly space nap with tiny legs",
    preview: false,
    lyrics: [
      "Fireflies blink. One star wiggles.",
      "It smells like banana pudding.",
      "S.S. Split lifts off the moss",
      "with rubber chickens (that is science).",
      "",
      "Verse",
      "Lord Vacuum wanted silent seesaws.",
      "Kids need bounce. Kids need play.",
      "Giggle-gravity comes back",
      "when dusty guests get asked to stay.",
      "",
      "Chorus",
      "If life gets slippery — make it a dance.",
      "Share your bounce. Invite the quiet.",
      "Jungle dirt or Peel Belt night,",
      "Friendship is the comet light.",
      "Slippery dance, slippery dance,",
      "Tiny legs on starry plants.",
      "",
      "Bridge",
      "Stars arrange a banana smile,",
      "then twinkle back to ordinary.",
      "Home is moss. Home is friends.",
      "Home is landing soft and merry.",
      "",
      "Soft reprise",
      "Share your bounce…",
      "Then close your eyes.",
    ],
    placement: "Chapter 4 (Space Peel); travel verse on the S.S. Split, reprise at dawn landing.",
  },
  {
    id: "one-free-hug",
    number: 5,
    title: "Hug Coupon, Please",
    subtitle: "Redeemable on any vine, any night",
    preview: false,
    lyrics: [
      "Vine-mail in the hammock,",
      "Glitter coupon, map, and stickers.",
      "Super Sprout Mart giggling doors—",
      "Carts with bumper-noses snickers.",
      "",
      "Verse",
      "Free samples, mild chaos,",
      "Coupons stuck to Grog like medals.",
      "Fluff can be a love language.",
      "Five helpers, infinite petals.",
      "",
      "Chorus",
      "One free hug, redeem anywhere.",
      "Same time tomorrow if you want.",
      "Leftover smoothie inventions,",
      "Always. Always. Jungle haunt.",
      "The grocery run can end.",
      "The friendship doesn't.",
      "",
      "Final hush",
      "Redeemed.",
      "Lights dim in the food court.",
      "Cape on the vine.",
      "Good night, Banana Boy.",
      "See you next peel.",
    ],
    placement: "Chapter 5 closer; pairs with Peel You Later as the pack lullaby.",
  },
];
