import type { Story } from "./content-types";

export const moonStory: Story = {
    id: "moon-forgot",
    title: "The Moon Forgot Its Glow",
    logline:
      "Tiny firefly Pip helps dark moon Luma remember how to shine.",
    cast: ["Pip", "Rook", "Luma", "Owl", "Sun", "Phob", "Deim"],
    lesson: "Even a little light, if you share it, can fill a whole night.",
    directorNote:
      "Ages 4–8 · Keep Luma dark until the finale · Small lights can fill a whole night.",
    emoji: "🌙",
    chapters: [
  {
    id: "night-went-gray",
    number: 1,
    title: "The Night Went Gray",
    preview: true,
    body: [
      "Once, the town slept under a silver moon.",
      "Then one night, the moon went soft and gray. Bedroom windows glowed, but the sky did not. A child hugged a pillow and whispered,",
      "“Mom… the moon looks tired.”",
      "High on a stone ledge, a tiny firefly named Pip watched the faded sky. Her own glow was only a honey-colored speck.",
      "“If the moon can’t shine,” Pip said, “what chance do I have?”",
      "She lifted off into the dark — one small spark in a big quiet town.",
    ],
  },
  {
    id: "rook-balloon-rocket",
    number: 2,
    title: "Rook and the Balloon Rocket",
    preview: false,
    body: [
      "Clank. String. Scrap metal.",
      "In a junkyard workshop, a raccoon named Rook wrestled a balloon rocket made of patches and hope.",
      "“Almost— whoa!”",
      "The rocket tipped. Pip steadied it with her tiny light.",
      "“Hey,” Rook said. “Tiny flashlight with wings.”",
      "“I’m Pip. The moon forgot how to glow. Kids can’t sleep.”",
      "Rook grinned. “Then we go get it. I’ve got a rocket. You’ve got spark.”",
      "“It’s a small spark,” Pip said.",
      "“Small sparks start big nights,” Rook answered. “Climb in.”",
      "They launched into the gray night.",
    ],
  },
  {
    id: "cloud-maze",
    number: 3,
    title: "The Cloud Maze",
    preview: false,
    body: [
      "Soft blue clouds twisted into a maze. The rocket bumped and spun.",
      "“I can’t see the path!” Rook cried.",
      "Pip flew ahead. Her light painted a golden trail through the fog.",
      "“This way… left… now straight!”",
      "They burst out above the clouds. Pip looked surprised she had led.",
      "“See?” Rook said. “Small light. Big path.”",
    ],
  },
  {
    id: "owl-shine",
    number: 4,
    title: "The Owl Who Kept the Shine",
    preview: false,
    body: [
      "On a cloud nest sat a round Owl, buried in stolen sparkles and stars.",
      "“Mine. All shiny. Mine.”",
      "“We need a little glow for the moon,” Rook said.",
      "“The moon can get a night-light,” the Owl sniffed, “like everyone else.”",
      "Pip’s glow flickered — then steadied.",
      "“Keeping light doesn’t make more light,” she said. “Sharing does.”",
      "She offered one tiny spark. The Owl hesitated… then dropped a single star into her hands.",
      "“…One,” he grumbled. “And bring it back if the moon’s rude.”",
    ],
  },
  {
    id: "dark-luma",
    number: 5,
    title: "Dark Luma",
    preview: false,
    body: [
      "They found Luma, Earth’s moon, sitting on a cloud like a cold stone — charcoal, dim, almost no light at all. One soft tear shone on her cheek.",
      "“Everyone looks up for light,” Luma whispered. “Tonight I have none.”",
      "“Then we’ll fix you,” Pip promised.",
      "Luma stayed dark.",
    ],
  },
  {
    id: "pip-tries",
    number: 6,
    title: "Pip Tries (and Tries)",
    preview: false,
    body: [
      "Pip tried everything she could invent.",
      "She poured star-sparks onto Luma. They fizzled and slid away. “They’re pretty,” Luma said. “They just aren’t mine.”",
      "She polished Luma with a tiny cloth. The cloth turned gray. Luma stayed dark.",
      "She gathered a firefly choir. Together they shone a bright beam. It painted Luma’s surface — but not her heart.",
      "She wrapped Luma in a glow blanket. Luma felt warmer… not brighter.",
      "She bounced Rook’s lantern-light with a shiny lid. The beam died in the dark.",
      "She painted a yellow smile on Luma’s cheek. It dripped into a sad gray smudge.",
      "She and Rook built a spark machine. It coughed gray smoke onto Luma’s nose. “Science is canceled,” Pip said.",
      "She even tried to be the moon herself — glowing as hard as she could. From town, she looked like one more star. Luma stayed a dark shape beside her.",
      "“You’re wonderful,” Luma said. “You’re not me.”",
      "Pip landed, tiny and tired. “Maybe,” she whispered, “I should ask other lights. Lights that already know how to shine.”",
    ],
  },
  {
    id: "other-lights",
    number: 7,
    title: "Advice from Other Lights",
    preview: false,
    body: [
      "Pip asked the lights who already knew how to shine. None of them could fix Luma — but each one tried kindly.",
      "The Lantern said: “Be steady. Shine without flickering.” Pip glowed steady beside Luma. Luma stayed dark. “Steady is good for paths,” Luma murmured. “I am not a path.”",
      "Jack the jack-o’-lantern said: “Carve a funny face! Seasonal shine!” Pip shaped a tiny smile of light. It faded into shadow. “I’m not a pumpkin,” Luma said, almost smiling.",
      "The Candle whispered: “Sometimes you don’t need big light. Just sit close.” Pip sat close and glowed gently. It was cozy. Luma stayed dark. “I feel less alone,” Luma said. “But I still can’t shine.”",
      "Glowcap the mushroom said: “Borrow the forest. Wear our shine.” Pip draped soft mushroom glow over Luma. Beautiful — for a moment. Then it sank into the dark. “Forest light belongs to the forest,” Luma said.",
      "The Streetlight boomed: “SIZE! Cover more ground! Brighter! Bigger!” Pip and Rook blasted every scrap of light toward Luma. The town blinked. Luma stayed a dark stone. “I am not a street,” Luma said quietly. “I am a moon who forgot.”",
      "The Stars chimed: “Come shine with us! Many small lights!” Pip joined them in a glittering net. It was gorgeous. It did not make Luma bright. “Borrowed glitter still isn’t me,” Luma said.",
      "Pip’s glow was thinner than ever. “Every light has an idea,” she whispered. “None of them fix you.”",
      "“Then ask someone bigger,” Rook said gently. “Someone who sees all the lights.”",
    ],
  },
  {
    id: "ask-the-sun",
    number: 8,
    title: "Ask the Sun",
    preview: false,
    body: [
      "“Night’s over,” Rook said. “Our ideas are over.”",
      "“Not over,” Pip said. “Just daytime. Who’s brighter than everyone?”",
      "They flew toward the rising Sun — big, warm, a little too sure of himself.",
      "“Whoa — little spark,” the Sun said. “Careful. I don’t do shade.”",
      "“Please,” Pip said. “Our moon — Luma — went dark. I asked a lantern, a jack-o’-lantern, a candle, a mushroom, a streetlight, the stars… Nothing stuck.”",
      "The Sun was quiet a moment. “Hmm. Moons aren’t my department. I shine. They… borrow.”",
      "“So you don’t have a fix?” Pip asked.",
      "“Not for someone your size,” the Sun said, honest and kind. “Not for someone her kind. But — Mars has two moons. They shine harder than any moons I know. Stubborn little lights. Go ask them.”",
      "“Mars?” Rook gulped. “That’s… a hike.”",
      "“Take the day wind,” the Sun said. “And don’t stare at me too long.”",
      "Pip nodded, scared and brave. “Thank you.”",
    ],
  },
  {
    id: "moons-of-mars",
    number: 9,
    title: "The Moons of Mars",
    preview: false,
    body: [
      "The balloon rocket rattled toward a red world. Two small moons tumbled nearby — Phob (bigger, bold) and Deim (smaller, soft).",
      "“Incoming firefly!” Phob called.",
      "“And a raccoon in a flying trash can,” Deim added. “Cute.”",
      "“I’m Pip,” she said. “Luma — Earth’s moon — lost her glow. The Sun said you shine brighter than any moons. Please… how?”",
      "“We don’t shine instead of Mars,” Phob said.",
      "“We shine with each other,” Deim said. “When one dims, the other stays close. Two small lights. One job.”",
      "“But I’m one light,” Pip said. “Luma’s alone.”",
      "“Then she isn’t fixed by brighter stuff poured on her,” Phob said.",
      "“She’s fixed when someone stays,” Deim said, “and shares a real spark. Not borrowed stars. Not lantern rules. Not streetlight size. Yours.”",
      "“I tried giving her everything else,” Pip whispered.",
      "“Everything else isn’t you,” Phob said.",
      "“Go home,” Deim said. “Sit with her in the dark. Offer the glow you were afraid was too small. That’s the Mars-moon way.”",
      "Pip’s eyes shone. “The failed tries… weren’t wrong,” she said. “They were practice.”",
      "“Then let’s practice being home,” Rook said.",
    ],
  },
  {
    id: "glow-comes-back",
    number: 10,
    title: "The Glow Comes Back",
    preview: false,
    body: [
      "Night again. Luma still dark. The town still waiting.",
      "Pip landed on Luma’s cheek — no jars, no machines, no paint, no borrowed shine.",
      "“I asked the lantern, Jack, the candle, Glowcap, the streetlight, and the stars,” Pip said. “They were kind. They couldn’t fix you. I asked the Sun. He didn’t know. I asked Mars’s moons. They did.”",
      "“What did they say?” Luma asked.",
      "“That small lights fix big dark… together. And that my spark was enough all along.”",
      "Pip pressed her own glow to Luma’s cheek.",
      "Warmth spread — slow, then silver-gold.",
      "Luma brightened.",
      "Windows lit. Children leaned out and cheered. Rook whooped from the balloon. Far below, the lantern flickered proudly, Jack grinned, the candle soft-smiled, Glowcap hummed, the streetlight pretended not to be impressed, and the stars winked like they knew.",
      "“I remember how,” Luma said.",
      "“Because you weren’t alone,” Pip answered.",
      "Far below, a child whispered, “Look! She’s back!”",
      "Pip turned to us, soft as a night-light:",
      "“Even a little light… if you share it… can fill a whole night.”",
    ],
  },
],
    songs: [
  {
    id: "little-fireflys-song",
    number: 1,
    title: "Little Firefly’s Song",
    subtitle: "Pip’s theme — a tiny spark that never gives up",
    preview: true,
    lyrics: [
      "Oh forest, tall and whispering green,",
      "Can you hear my tiny voice tonight?",
      "I’m just a spark, a little gleam,",
      "But I still fill the dark with light.",
      "",
      "Dear moon, so high and silver-round,",
      "You watch me dance from far away.",
      "Even when the night feels heavy,",
      "You never look the other way.",
      "",
      "Chorus",
      "I will glow, I will glow, I will never give up,",
      "Happiness lives in this little cup",
      "Of light I carry in my heart.",
      "When the wind is strong and the path is long,",
      "I keep on shining, I keep on strong.",
      "I will glow, I will glow, I will never give up.",
      "",
      "The trees lean in and the leaves all hush,",
      "The crickets pause to hear me sing.",
      "I tell them joy is not a race,",
      "It’s the tiny light I bring.",
      "",
      "The moon just smiles her quiet smile,",
      "And paints the world in silver-blue.",
      "She says, “Keep going, little one—",
      "The dark was made for you.”",
      "",
      "Chorus",
      "I will glow, I will glow, I will never give up,",
      "Happiness lives in this little cup",
      "Of light I carry in my heart.",
      "When the wind is strong and the path is long,",
      "I keep on shining, I keep on strong.",
      "I will glow, I will glow, I will never give up.",
      "",
      "So forest, hold me in your arms,",
      "And moon, keep watching from above.",
      "I’ll twinkle on through every night",
      "With happiness and love.",
      "",
      "I will glow…",
      "I will glow…",
      "I will never give up.",
    ],
    placement: "Soft verse in Chapter 1; chorus under the fail montage; full song at the finale.",
  },
  {
    id: "lumas-sad-song",
    number: 2,
    title: "Luma’s Sad Song",
    subtitle: "When the moon feels dark and forgotten",
    preview: true,
    lyrics: [
      "I used to silver every street,",
      "I used to hush the world to sleep.",
      "Now I’m a shadow, soft and gray—",
      "A quiet light that slipped away.",
      "",
      "The children wait. I hear them sigh.",
      "I want to shine. I don’t know why",
      "My glow went small, my glow went still…",
      "I hang alone above the hill.",
      "",
      "Chorus",
      "I’m dark tonight, I’m dark tonight,",
      "A moon without her borrowed light.",
      "If someone sees me as I am—",
      "Not bright, just me—please understand:",
      "I’m dark tonight, I’m dark tonight,",
      "But I am still the moon, all right.",
      "",
      "I watched the sparks and stars go by.",
      "They tried to paint me in the sky.",
      "Their kindness landed, soft and true…",
      "But none of them could make me new.",
      "",
      "A tiny voice keeps calling near—",
      "A little glow that stays right here.",
      "She doesn’t fix me like a lamp…",
      "She sits with me inside the damp.",
      "",
      "Chorus",
      "I’m dark tonight, I’m dark tonight,",
      "A moon without her borrowed light.",
      "If someone sees me as I am—",
      "Not bright, just me—please understand:",
      "I’m dark tonight, I’m dark tonight,",
      "But I am still the moon, all right.",
      "",
      "Maybe the dark is not the end.",
      "Maybe it means I need a friend.",
      "Until my silver finds its way…",
      "I’ll hold this night. I’ll wait. I’ll stay.",
      "",
      "I’m dark tonight…",
      "I’m dark tonight…",
      "But I am still the moon.",
    ],
    placement: "When Pip first finds dark Luma (Chapter 5). Soft reprise under failed helps.",
  },
  {
    id: "when-the-fairy-gets-sad",
    number: 3,
    title: "When the Fairy Gets Sad",
    subtitle: "A song the forest animals sing to Pip",
    preview: false,
    lyrics: [
      "Owl in the oak, soft and low:",
      "Little fairy, dry your eyes.",
      "The night is big, but you are not alone—",
      "We are here beneath these skies.",
      "",
      "Rabbit in the clover, gentle and small:",
      "If your wings feel heavy tonight,",
      "Rest them here on the mossy ground.",
      "We’ll keep you safe till morning light.",
      "",
      "Chorus",
      "Don’t dim your glow, don’t hide your spark,",
      "The forest loves you in the dark.",
      "When your heart feels small and blue,",
      "We will sing until you’re you.",
      "Don’t give up, little shining one—",
      "The moon is watching, the night isn’t done.",
      "",
      "Deer by the stream, quiet and kind:",
      "Even stars get tired sometimes.",
      "They still come back and light the way.",
      "You can too, in your own time.",
      "",
      "Frog on the lily, warm and true:",
      "Sadness visits, then it goes.",
      "We will croak and hop and stay",
      "Until your little light grows.",
      "",
      "Chorus",
      "Don’t dim your glow, don’t hide your spark,",
      "The forest loves you in the dark.",
      "When your heart feels small and blue,",
      "We will sing until you’re you.",
      "Don’t give up, little shining one—",
      "The moon is watching, the night isn’t done.",
      "",
      "All the animals together:",
      "So close your eyes if you need to rest.",
      "We’ll hum the trees and hold you tight.",
      "Tomorrow the sun will find you again—",
      "And so will we, with all our light.",
      "",
      "Don’t dim your glow…",
      "Don’t hide your spark…",
      "We are here.",
      "You are loved.",
      "Don’t give up.",
    ],
    placement: "Comfort number when Pip feels her spark is too small.",
  },
  {
    id: "stars-and-moon-carry-me",
    number: 4,
    title: "Stars and Moon, Carry Me",
    subtitle: "The travel song on the way to Mars",
    preview: false,
    lyrics: [
      "Forest, I’m lifting past your trees,",
      "Wings full of sparkle, heart full of breeze.",
      "The night I loved is falling behind—",
      "But the moon still follows, kind and kind.",
      "",
      "Little stars, light my trail,",
      "Silver crumbs on a cosmic sail.",
      "Moon, don’t hide, stay close and bright—",
      "I’m flying farther than I’ve flown tonight.",
      "",
      "Chorus",
      "Stars and moon, carry me,",
      "Over the dark and the deep black sea.",
      "I won’t give up, I won’t grow small—",
      "Happiness travels with me after all.",
      "Glow, little glow, all the way to Mars,",
      "You are my map, you are my stars.",
      "",
      "The Earth grows round and blue and far,",
      "A marble spinning like a jar",
      "Of every song the forest knew.",
      "I tuck that song inside me too.",
      "",
      "Phobos winks and Deimos hums,",
      "Two shy moons saying, “Here she comes.”",
      "Red dust waits like a sleepy shore—",
      "But I’m not lonely anymore.",
      "",
      "Chorus",
      "Stars and moon, carry me,",
      "Over the dark and the deep black sea.",
      "I won’t give up, I won’t grow small—",
      "Happiness travels with me after all.",
      "Glow, little glow, all the way to Mars,",
      "You are my map, you are my stars.",
      "",
      "Final chorus",
      "Stars and moon, carry me home",
      "And carry me onward, wherever I roam.",
      "I won’t give up, I won’t grow dim—",
      "The forest’s love is still in me, within.",
      "Glow, little glow, on a brand-new world…",
      "Fairy and firefly, wings unfurled.",
    ],
    placement: "Balloon-rocket flight from Earth to Mars (after the Sun, before Phob & Deim).",
  },
  {
    id: "song-for-a-sad-moon",
    number: 5,
    title: "Song for a Sad Moon",
    subtitle: "Comfort for Luma while she stays dark",
    preview: false,
    lyrics: [
      "Hello, moon, why so still?",
      "Your silver face looks tired tonight.",
      "Did the clouds sit heavy on you,",
      "Or did you lose a piece of light?",
      "",
      "You don’t have to shine the whole sky alone.",
      "Even you can rest a little while.",
      "The stars will keep the dark from feeling empty",
      "Until you find your quiet smile.",
      "",
      "If you feel far, I’m still down here.",
      "If you feel dim, I see you anyway.",
      "Sad moons still matter. Sad moons still guide.",
      "You can be soft and still light the way.",
      "",
      "So lean on the night if you need to.",
      "Cry silver if you have to cry.",
      "When you’re ready, rise again slowly.",
      "We’ll wait. We’re not saying goodbye.",
      "",
      "Glow when you can. Rest when you can’t.",
      "You’re loved even when you fade.",
      "Sad moon, you’re still our moon.",
      "You don’t have to be perfect to stay.",
    ],
    placement: "Pip (or the town) sings this to dark Luma. Pairs with Luma’s Sad Song.",
  },
  {
    id: "things-that-glow",
    number: 6,
    title: "Things That Glow",
    subtitle: "Theme song — glow doesn’t have to be giant",
    preview: false,
    lyrics: [
      "Fireflies write letters in the grass.",
      "Night-lights hum in a sleepy room.",
      "A jar of lightning bugs. A porch lamp.",
      "A smile that finds you in the gloom.",
      "",
      "The moon hangs like a lantern.",
      "Stars pin sparkles to the black.",
      "A candle on a windowsill.",
      "The eyes of a cat coming back.",
      "",
      "Dew can catch a little sun.",
      "A screen can make a tiny day.",
      "A heart can light a hallway",
      "When someone kind has something to say.",
      "",
      "Glow doesn’t have to be giant.",
      "Glow can be a speck, a spark, a crumb.",
      "Glow can be a bug, a moon, a laugh,",
      "Or the warmth when someone says, “I’m here. Come.”",
      "",
      "So if the dark feels bigger than you,",
      "Remember all the things that shine:",
      "Bugs and moons and kitchen lights",
      "And the brave little glow that’s mine.",
    ],
    placement: "Opening theme or end-credits; montage under Pip’s tour of lights.",
  },
],
  };
