import type { Song } from "./content-types";

export const honeybeeSongs: Song[] = [
  {
    id: "buzz-loud",
    number: 1,
    title: "Buzz Loud",
    subtitle: "Comic to soft — Buzz learns volume has a bedtime",
    preview: true,
    lyrics: [
      "BUZZ LOUD! BUZZ LOUD!",
      "I shake the honeycomb walls!",
      "Midnight practice, morning proud—",
      "I never learned the quiet calls!",
      "",
      "(spoken, softer)",
      "Queen says dawn needs wake-up…",
      "Night needs whisper…",
      "",
      "Verse 2 — a little softer",
      "Buzz… loud…? maybe medium…",
      "Earmuffs waiting on the crown.",
      "I can help without the thunder—",
      "I can turn my volume down.",
      "",
      "Verse 3 — cradle-soft",
      "Softer than proud,",
      "Softer than busy,",
      "Softer than look at me.",
      "Half a notch… half a notch…",
      "Quiet places set me free.",
      "",
      "Chorus — bridge to Soft Alarm",
      "I will glow… I mean, I will hum…",
      "Not to startle, just to keep",
      "Every tiny dreamer safe",
      "While the hive is deep in sleep.",
      "Buzz loud when morning rings—",
      "Buzz soft when moonlight sings.",
      "Different times, different wings.",
      "",
      "Final hush",
      "Buzz… soft…",
      "Buzz… soft…",
      "I'm learning when.",
    ],
    placement: "Ch 1–2 comic loud; Ch 3–4 softening; final chorus bridges into Soft Alarm.",
  },
  {
    id: "petal-still",
    number: 2,
    title: "Petal Still",
    subtitle: "Sol the sunflower teaches honest listening",
    preview: false,
    lyrics: [
      "Tall Sol, sunflower friend,",
      "Petals open, night wind thin.",
      "Buzz me true, the flower said,",
      "My petals tell you what's within.",
      "",
      "Loud note — shiver, shiver,",
      "Petals tremble, can't stay still.",
      "Soft note — quiet river,",
      "Petals listening on the hill.",
      "",
      "Chorus",
      "Petal still, petal still,",
      "That's the volume kindness knows.",
      "Not a push, an invitation—",
      "That's the way a soft note grows.",
      "Petal still, petal still,",
      "Hold the gold without the spill.",
      "",
      "Bridge",
      "First true soft note in my chest,",
      "Like a coin of gentle light.",
      "Crickets pause to hear it rest…",
      "I don't have to win the night.",
      "",
      "Chorus",
      "Petal still, petal still,",
      "That's the volume kindness knows.",
      "Not a push, an invitation—",
      "That's the way a soft note grows.",
      "",
      "Soft reprise",
      "Petal still…",
      "Almost lullaby…",
      "Petal still.",
    ],
    placement: "Chapter 5 (Sol); soft reprise in Chapter 7 (Almost-Lullaby).",
  },
  {
    id: "soft-alarm-song",
    number: 3,
    title: "Soft Alarm",
    subtitle: "The lullaby buzz that lets the hive sleep",
    preview: false,
    lyrics: [
      "Soft alarm, soft alarm,",
      "Not a shout across the comb—",
      "Just a hum that holds the dark",
      "And tells the tired hearts: you're home.",
      "",
      "Verse — soft (Ch 5–6)",
      "Follow, don't lead the choir.",
      "Harmony is more than loud.",
      "Slip your note in beside them—",
      "Belonging is allowed.",
      "",
      "Chorus — full (Ch 9)",
      "Soft alarm, soft alarm,",
      "Earmuffs unused on the hook.",
      "Queen is smiling, nursery dreaming,",
      "Buzz has learned another book:",
      "Morning voice and midnight grace—",
      "Two jobs living in one face.",
      "Soft alarm, soft alarm…",
      "Kindness keeps the sleeping place.",
      "",
      "Bridge",
      "Soft isn't small.",
      "Soft is kind.",
      "Different times need different volumes.",
      "I keep my loud for dawn to find.",
      "",
      "Tiny reprise (Ch 10)",
      "Dawn on purpose — bright and clear.",
      "I didn't lose my loud, my dear.",
      "Some nights need a soft alarm…",
      "So tomorrow can sing from here.",
      "",
      "Soft alarm…",
      "Soft alarm…",
      "Good night, hive.",
    ],
    placement: "Soft verse Ch 5–6; full song Ch 9; tiny reprise Ch 10 closer.",
  },
];
