import type { Song } from "./content-types";

export const lumiSongs: Song[] = [
  {
    id: "hi-im-lumi-song",
    number: 1,
    title: "Hi, I’m Lumi",
    subtitle: "A hello from the sparkle-dress fairy",
    preview: true,
    lyrics: [
      "Hi, I’m Lumi — red and snowy hair,",
      "Wings like sugar, lights in the air.",
      "Come along, the forest knows my name.",
      "Every day a new adventure game.",
      "",
      "Chorus",
      "Big adventures, kind hearts,",
      "A brighter world from little starts.",
      "Foxy close and fireflies near—",
      "You are welcome. You are here.",
    ],
    placement: "Chapter 1 greeting; soft wave under the title card.",
  },
  {
    id: "kindness-biggest-magic",
    number: 2,
    title: "Kindness Makes the Biggest Magic",
    subtitle: "The promise song for Lumi’s circle",
    preview: false,
    lyrics: [
      "Benny, Foxy, Squirrel, Ollie too,",
      "A raccoon peeking from the dew.",
      "Circle up on clover ground—",
      "Little friends can hold a town.",
      "",
      "Chorus",
      "Kindness makes the biggest magic.",
      "Not a spell you have to shout.",
      "Sit with someone. Share the looking.",
      "That is how the glow comes out.",
      "",
      "New friends, new places, new adventures…",
      "Then the treehouse lights go low.",
      "Goodnight, kind hearts. Sleep in sparkle.",
      "Tomorrow we will glow.",
    ],
    placement: "Chapter 2 circle; reprise at the treehouse goodnight.",
  },
];
