import type { Chapter } from "./content-types";

export const bananaChapters: Chapter[] = [
  {
    id: "coconut-crackdown",
    number: 1,
    title: "Coconut Crackdown",
    preview: true,
    body: [
      "Once upon a time in Giggle Jungle — Morning.",
      "Sunbeams poke through palm leaves. Birds whistle silly tunes. Somewhere, a coconut falls with a soft bonk.",
      "BENNY / BANANA BOY — fat yellow banana, tiny muscular legs, leaf cape fluttering, blue mask and gloves — stretches on a vine hammock.",
      "“Ahhh. Another peaceful day in Giggle Jungle. No villains. No sticky schemes. Just me, my cape, and—” said Banana Boy.",
      "CRACK! A coconut smashes into the dirt beside him. He flips out of the hammock, cape over his eyes.",
      "“—and flying breakfast?!” said Banana Boy.",
      "“Thanks, Grog. But first—” said Banana Boy.",
      "“Captain Coco? But he helped us against the Durian Doomsday sticky-bomb!” said Banana Boy.",
      "“Captain Coco! It's me — Banana Boy! Friend of fruit! Protector of peels! Can we talk?” said Banana Boy.",
      "“Those judges look bribe-able with snacks.” said Monkey 2.",
      "“That was… ridiculous.” said Captain Coco.",
      "“Neither was being stuck alone in a fort. Remember when you helped stop Durian Doomsday? You said fruit stick together.” said Grog.",
      "Banana Boy and Captain Coco sit on the cliff edge, dangling tiny legs and coconut boots.",
      "“Deal!” said everyone.",
      "Once upon a time in Giggle Jungle — Night.",
      "Stars twinkle. Fireflies blink Morse-code giggles. Banana Boy hangs in his vine hammock again. Nearby, the Purple Monkey Squad snores in a coconut-shell bunk bed. Grog snores louder. Duke Durian uses a soft pillow over his spikes. Captain Coco patrols once… then joins the snoring pile with a smile.",
      "“Remember, friends: when life gets hard as a coconut… crack it open with kindness. And maybe a foam cannon. See you next peel!” said Banana Boy.",
      "He winks. His leaf cape flutters. A tiny coconut with a parachute drifts past, painting a heart on a leaf.",
    ],
  },
  {
    id: "pineapple-protocol",
    number: 2,
    title: "Pineapple Protocol",
    preview: false,
    body: [
      "Once upon a time in Giggle Jungle — Clearing — Day.",
      "Birds chirp. Leaves rustle. A giant corkboard stands in the middle of the clearing, covered in string, leaf sticky-notes, and a drawing of a pineapple wearing sunglasses.",
      "BANANA BOY paces in front of the board, leaf cape swishing, blue gloves tapping his chin.",
      "“Okay, team. After Coconut Crackdown, we learned shells and softness can be friends. But today… we face something pricklier. Something… *protocol-y*.” said Banana Boy.",
      "PURPLE MONKEY SQUAD sits in tiny school desks made of stumps. GROG squeezes into a desk and breaks it. He shrugs apologetically. DUKE DURIAN takes notes with a thorn pencil. CAPTAIN COCO sips coconut water and listens.",
      "“Is protocol a fruit?” said Monkey 1.",
      "Once upon a time in Pineapple Plaza — Midday.",
      "“The Pineapple Protocol keeps everyone safe. Safe means ordered. Ordered means no surprises. No surprises means no… *Durian Doomsday* sticky chaos. No coconut cannon confusion. Only perfect rows.” said General Grid.",
      "Once upon a time in Pineapple Plaza — Continuous.",
      "Banana Boy's team joins… but Banana Boy's tiny legs take three steps for every one of Grog's. Duke Durian pivots on a spike and spins like a top — gently. Captain Coco adds coconut percussion that is slightly offbeat on purpose.",
      "“General Grid: best… shiny sunglasses vibes?” said Monkey 3.",
      "The maze of statues rolls aside. Animals peek out. The beetle band plays a looser tune — still squeaky, but swingy.",
      "“We'll help you un-laminate life. A little at a time.” said Banana Boy.",
      "“Permission granted. Wiggling is now mandatory… optionally.” said General Grid.",
      "They wiggle. A pineapple statue's sunglasses slip into a smile shape. The beetle band plays one squeaky note of triumph.",
      "“Best protocol ever.” said Monkey 1.",
      "“Playtocol. Get it right, Monkey One.” said Duke Durian.",
      "“Playtocol forever!” said Monkey 1.",
    ],
  },
  {
    id: "blender-of-doom",
    number: 3,
    title: "Blender of Doom",
    preview: false,
    body: [
      "Once upon a time in Giggle Jungle Smoothie Shack — Morning.",
      "A cozy shack built from bamboo and leaf thatch. A hand-painted sign swings: GROG'S GENTLE BLENDS. Inside, GROG hums while tossing berries into a small, friendly blender with googly eyes named WHIRR-Y.",
      "“Blendy-ready!” said Whirr-y.",
      "BANANA BOY sits at the counter, leaf cape tucked neatly, sipping a banana-coconut swirl.",
      "“Grog, this is the best smoothie since… forever. Tiny legs feel extra springy!” said Banana Boy.",
      "PURPLE MONKEY SQUAD shares one giant cup with five straws. Chaos. Sticky faces. Happiness.",
      "Once upon a time in Jungle Canopy — Continuous.",
      "“Mess is just flavor that hasn't found its destiny!” said MixMaster Max.",
      "“I can provide a blending schedule that includes breaks for giggles.” said General Grid.",
      "“A tie? My cyclone had *drama*!” said MixMaster Max.",
      "Once upon a time in Round Three — The Swirl Surf.",
      "“Hold red button and tell a joke?!” said Duke Durian.",
      "The Blender of Doom — now wearing a “PARTY TRAINEE” sticker from General Grid — serves soft-serve swirls into cups. Whirr-y beeps proudly beside it like a little sibling.",
      "“You're weird, Banana Boy.” said MixMaster Max.",
      "“Weird is a superfood.” said Banana Boy.",
      "He stands, leaf cape catching moonlight.",
      "“When something feels too whirl-y, hit the red button of kindness and tell a joke. Stay blended with your friends — not against them. See you on the next adventure!” said Banana Boy.",
      "Whirr-y and the reformed Blender of Doom beep a harmony. The monkeys snore in the ball pit. Grog drapes a giant leaf blanket over everyone.",
    ],
  },
  {
    id: "space-peel",
    number: 4,
    title: "Space Peel",
    preview: false,
    body: [
      "Once upon a time in Giggle Jungle — Night (Opening).",
      "Fireflies blink. The Purple Monkey Squad lies on their backs counting stars. One monkey counts the same star twelve times.",
      "“Forty-eleven… forty-twelve…” said Monkey 1.",
      "“Pretty sure that's not how numbers work. But your enthusiasm? Ten out of ten.” said Banana Boy.",
      "GROG points up. A streak of light crosses the sky — not a normal shooting star. It wiggles. It beeps. It smells faintly like… banana pudding?",
      "“That star has drama.” said Duke Durian.",
      "Once upon a time in S.S. Split — Cockpit — Night.",
      "“I packed rubber chickens. For science.” said Monkey 2.",
      "“Welcome, peel-heroes! Lord Vacuum sucked our playground's giggle-gravity! Now our seesaw only see… not saw.” said Splootling Mayor.",
      "“Tidy can be nice. Silent forever? Not nice. Kids need bounce!” said Banana Boy.",
      "Once upon a time in Round One — Float Tag.",
      "They sit. Silence. Stars hum softly. Monkey 1's tummy growls like a tuba. Everyone holds it together… until Grog's gentle snore (he fell asleep) sounds like a friendly foghorn. Laughter explodes.",
      "“JANITOR OF JOY! JANITOR OF JOY!” said everyone.",
      "Once upon a time in Giggle Jungle — Dawn Landing.",
      "The S.S. Split settles into moss. Birds welcome them with off-key fanfares. Whirr-y the blender beeps from the shack. The Blender of Doom (Party Trainee) wears a “Welcome Home” banner.",
      "Banana Boy hops out. Tiny legs hit jungle dirt. He kisses the ground (cartoon smack), then spits a leaf. Everyone laughs.",
      "“Whether you're in the jungle or the Peel Belt, share your bounce. Invite the dusty guests. And if life gets slippery — make it a dance. Until next peel, friends!” said Banana Boy.",
      "The Comet Compass glows toward the group hug. Stars above arrange briefly into a banana smile, then twinkle back to normal.",
    ],
  },
  {
    id: "grocery-gauntlet",
    number: 5,
    title: "Grocery Gauntlet",
    preview: false,
    body: [
      "Once upon a time in Giggle Jungle — Morning.",
      "A vine-mail envelope drops onto Banana Boy's hammock. Inside: a glittery coupon and a map.",
      "“You and your friends are invited to the grand opening of **SUPER SPROUT MART** — the friendliest grocery in the fruitiverse! Free samples! Free stickers! Free… mild chaos?” said Banana Boy.",
      "PURPLE MONKEY SQUAD appears upside down from a branch.",
      "“Did it say free samples?” said Monkey 1.",
      "“Did it say stickers?” said Monkey 2.",
      "A cheerful mega-market shaped like a giant shopping basket. Automatic doors open with a giggle sound effect. Greeters are anthropomorphic shopping carts with googly eyes and soft bumper noses: the CART CREW.",
      "Wind whooshes. Paper coupons swirl — soft paper, rounded edges. The team links arms. Grog becomes a gentle windbreak. Coupons stick to his fur like funny medals.",
      "“I am pudding now. It is my destiny. (beat) Temporary destiny!” said Bunch.",
      "“I heard there was fluff. Fluff is my love language now.” said Lord Vacuum.",
      "“Five goofy helpers, one brain cell sometimes, infinite heart.” said Clue 3.",
      "Once upon a time in Super Sprout Mart — Food Court — Sunset Light Through Windows.",
      "“And I'll file this under Successful Ground Missions.” said Commander Nana.",
      "“Same time tomorrow for leftover smoothie invention?” said Grog.",
      "“Always.” said Banana Boy.",
      "A cart from Super Sprout Mart rolls by on a delivery vine, honks a giggle horn, and drops a thank-you coupon: ONE FREE HUG, REDEEM ANYWHERE.",
      "“Redeemed!” said everyone.",
      "The end of this grocery run — but never of friendship.",
    ],
  },
];
