import type { Song } from "./content-types";

export const moonSongs: Song[] = [
  {
    id: "little-fireflys-song",
    number: 1,
    title: "Little Firefly’s Song",
    subtitle: "Pip’s theme — a tiny spark that never gives up",
    preview: true,
    lyrics: [
      "Oh forest, tall and whispering green,",
      "Can you hear my tiny voice tonight?",
      "I’m just a spark, a little gleam,",
      "But I still fill the dark with light.",
      "",
      "Dear moon, so high and silver-round,",
      "You watch me dance from far away.",
      "Even when the night feels heavy,",
      "You never look the other way.",
      "",
      "Chorus",
      "I will glow, I will glow, I will never give up,",
      "Happiness lives in this little cup",
      "Of light I carry in my heart.",
      "When the wind is strong and the path is long,",
      "I keep on shining, I keep on strong.",
      "I will glow, I will glow, I will never give up.",
      "",
      "The trees lean in and the leaves all hush,",
      "The crickets pause to hear me sing.",
      "I tell them joy is not a race,",
      "It’s the tiny light I bring.",
      "",
      "The moon just smiles her quiet smile,",
      "And paints the world in silver-blue.",
      "She says, “Keep going, little one—",
      "The dark was made for you.”",
      "",
      "Chorus",
      "I will glow, I will glow, I will never give up,",
      "Happiness lives in this little cup",
      "Of light I carry in my heart.",
      "When the wind is strong and the path is long,",
      "I keep on shining, I keep on strong.",
      "I will glow, I will glow, I will never give up.",
      "",
      "So forest, hold me in your arms,",
      "And moon, keep watching from above.",
      "I’ll twinkle on through every night",
      "With happiness and love.",
      "",
      "I will glow…",
      "I will glow…",
      "I will never give up.",
    ],
    placement: "Soft verse in Chapter 1; chorus under the fail montage; full song at the finale.",
  },
  {
    id: "lumas-sad-song",
    number: 2,
    title: "Luma’s Sad Song",
    subtitle: "When the moon feels dark and forgotten",
    preview: true,
    lyrics: [
      "I used to silver every street,",
      "I used to hush the world to sleep.",
      "Now I’m a shadow, soft and gray—",
      "A quiet light that slipped away.",
      "",
      "The children wait. I hear them sigh.",
      "I want to shine. I don’t know why",
      "My glow went small, my glow went still…",
      "I hang alone above the hill.",
      "",
      "Chorus",
      "I’m dark tonight, I’m dark tonight,",
      "A moon without her borrowed light.",
      "If someone sees me as I am—",
      "Not bright, just me—please understand:",
      "I’m dark tonight, I’m dark tonight,",
      "But I am still the moon, all right.",
      "",
      "I watched the sparks and stars go by.",
      "They tried to paint me in the sky.",
      "Their kindness landed, soft and true…",
      "But none of them could make me new.",
      "",
      "A tiny voice keeps calling near—",
      "A little glow that stays right here.",
      "She doesn’t fix me like a lamp…",
      "She sits with me inside the damp.",
      "",
      "Chorus",
      "I’m dark tonight, I’m dark tonight,",
      "A moon without her borrowed light.",
      "If someone sees me as I am—",
      "Not bright, just me—please understand:",
      "I’m dark tonight, I’m dark tonight,",
      "But I am still the moon, all right.",
      "",
      "Maybe the dark is not the end.",
      "Maybe it means I need a friend.",
      "Until my silver finds its way…",
      "I’ll hold this night. I’ll wait. I’ll stay.",
      "",
      "I’m dark tonight…",
      "I’m dark tonight…",
      "But I am still the moon.",
    ],
    placement: "When Pip first finds dark Luma (Chapter 5). Soft reprise under failed helps.",
  },
  {
    id: "when-the-fairy-gets-sad",
    number: 3,
    title: "When the Fairy Gets Sad",
    subtitle: "A song the forest animals sing to Pip",
    preview: false,
    lyrics: [
      "Owl in the oak, soft and low:",
      "Little fairy, dry your eyes.",
      "The night is big, but you are not alone—",
      "We are here beneath these skies.",
      "",
      "Rabbit in the clover, gentle and small:",
      "If your wings feel heavy tonight,",
      "Rest them here on the mossy ground.",
      "We’ll keep you safe till morning light.",
      "",
      "Chorus",
      "Don’t dim your glow, don’t hide your spark,",
      "The forest loves you in the dark.",
      "When your heart feels small and blue,",
      "We will sing until you’re you.",
      "Don’t give up, little shining one—",
      "The moon is watching, the night isn’t done.",
      "",
      "Deer by the stream, quiet and kind:",
      "Even stars get tired sometimes.",
      "They still come back and light the way.",
      "You can too, in your own time.",
      "",
      "Frog on the lily, warm and true:",
      "Sadness visits, then it goes.",
      "We will croak and hop and stay",
      "Until your little light grows.",
      "",
      "Chorus",
      "Don’t dim your glow, don’t hide your spark,",
      "The forest loves you in the dark.",
      "When your heart feels small and blue,",
      "We will sing until you’re you.",
      "Don’t give up, little shining one—",
      "The moon is watching, the night isn’t done.",
      "",
      "All the animals together:",
      "So close your eyes if you need to rest.",
      "We’ll hum the trees and hold you tight.",
      "Tomorrow the sun will find you again—",
      "And so will we, with all our light.",
      "",
      "Don’t dim your glow…",
      "Don’t hide your spark…",
      "We are here.",
      "You are loved.",
      "Don’t give up.",
    ],
    placement: "Comfort number when Pip feels her spark is too small.",
  },
  {
    id: "stars-and-moon-carry-me",
    number: 4,
    title: "Stars and Moon, Carry Me",
    subtitle: "The travel song on the way to Mars",
    preview: false,
    lyrics: [
      "Forest, I’m lifting past your trees,",
      "Wings full of sparkle, heart full of breeze.",
      "The night I loved is falling behind—",
      "But the moon still follows, kind and kind.",
      "",
      "Little stars, light my trail,",
      "Silver crumbs on a cosmic sail.",
      "Moon, don’t hide, stay close and bright—",
      "I’m flying farther than I’ve flown tonight.",
      "",
      "Chorus",
      "Stars and moon, carry me,",
      "Over the dark and the deep black sea.",
      "I won’t give up, I won’t grow small—",
      "Happiness travels with me after all.",
      "Glow, little glow, all the way to Mars,",
      "You are my map, you are my stars.",
      "",
      "The Earth grows round and blue and far,",
      "A marble spinning like a jar",
      "Of every song the forest knew.",
      "I tuck that song inside me too.",
      "",
      "Phobos winks and Deimos hums,",
      "Two shy moons saying, “Here she comes.”",
      "Red dust waits like a sleepy shore—",
      "But I’m not lonely anymore.",
      "",
      "Chorus",
      "Stars and moon, carry me,",
      "Over the dark and the deep black sea.",
      "I won’t give up, I won’t grow small—",
      "Happiness travels with me after all.",
      "Glow, little glow, all the way to Mars,",
      "You are my map, you are my stars.",
      "",
      "Final chorus",
      "Stars and moon, carry me home",
      "And carry me onward, wherever I roam.",
      "I won’t give up, I won’t grow dim—",
      "The forest’s love is still in me, within.",
      "Glow, little glow, on a brand-new world…",
      "Fairy and firefly, wings unfurled.",
    ],
    placement: "Balloon-rocket flight from Earth to Mars (after the Sun, before Phob & Deim).",
  },
  {
    id: "song-for-a-sad-moon",
    number: 5,
    title: "Song for a Sad Moon",
    subtitle: "Comfort for Luma while she stays dark",
    preview: false,
    lyrics: [
      "Hello, moon, why so still?",
      "Your silver face looks tired tonight.",
      "Did the clouds sit heavy on you,",
      "Or did you lose a piece of light?",
      "",
      "You don’t have to shine the whole sky alone.",
      "Even you can rest a little while.",
      "The stars will keep the dark from feeling empty",
      "Until you find your quiet smile.",
      "",
      "If you feel far, I’m still down here.",
      "If you feel dim, I see you anyway.",
      "Sad moons still matter. Sad moons still guide.",
      "You can be soft and still light the way.",
      "",
      "So lean on the night if you need to.",
      "Cry silver if you have to cry.",
      "When you’re ready, rise again slowly.",
      "We’ll wait. We’re not saying goodbye.",
      "",
      "Glow when you can. Rest when you can’t.",
      "You’re loved even when you fade.",
      "Sad moon, you’re still our moon.",
      "You don’t have to be perfect to stay.",
    ],
    placement: "Pip (or the town) sings this to dark Luma. Pairs with Luma’s Sad Song.",
  },
  {
    id: "things-that-glow",
    number: 6,
    title: "Things That Glow",
    subtitle: "Theme song — glow doesn’t have to be giant",
    preview: false,
    lyrics: [
      "Fireflies write letters in the grass.",
      "Night-lights hum in a sleepy room.",
      "A jar of lightning bugs. A porch lamp.",
      "A smile that finds you in the gloom.",
      "",
      "The moon hangs like a lantern.",
      "Stars pin sparkles to the black.",
      "A candle on a windowsill.",
      "The eyes of a cat coming back.",
      "",
      "Dew can catch a little sun.",
      "A screen can make a tiny day.",
      "A heart can light a hallway",
      "When someone kind has something to say.",
      "",
      "Glow doesn’t have to be giant.",
      "Glow can be a speck, a spark, a crumb.",
      "Glow can be a bug, a moon, a laugh,",
      "Or the warmth when someone says, “I’m here. Come.”",
      "",
      "So if the dark feels bigger than you,",
      "Remember all the things that shine:",
      "Bugs and moons and kitchen lights",
      "And the brave little glow that’s mine.",
    ],
    placement: "Opening theme or end-credits; montage under Pip’s tour of lights.",
  },
];
