import type { Song } from "./content-types";

export const marsSongs: Song[] = [
  {
    id: "stars-and-moon-carry-me-mars",
    number: 1,
    title: "Stars and Moon, Carry Me",
    subtitle: "Pip’s travel song all the way to Mars",
    preview: true,
    lyrics: [
      "Forest, I’m lifting past your trees,",
      "Wings full of sparkle, heart full of breeze.",
      "The night I loved is falling behind—",
      "But the moon still follows, kind and kind.",
      "",
      "Little stars, light my trail,",
      "Silver crumbs on a cosmic sail.",
      "Moon, don’t hide, stay close and bright—",
      "I’m flying farther than I’ve flown tonight.",
      "",
      "Chorus",
      "Stars and moon, carry me,",
      "Over the dark and the deep black sea.",
      "I won’t give up, I won’t grow small—",
      "Happiness travels with me after all.",
      "Glow, little glow, all the way to Mars,",
      "You are my map, you are my stars.",
    ],
    placement: "Chapter 1 lift-off; hum under the flight in Chapter 2.",
  },
  {
    id: "red-dust-goodnight",
    number: 2,
    title: "Red Dust Goodnight",
    subtitle: "A hush for a brand-new world",
    preview: false,
    lyrics: [
      "Red dust, settle soft.",
      "Stone, hold my tiny light.",
      "I came a long, long way",
      "to say goodnight.",
      "",
      "Moons of Mars, blink twice.",
      "Earth-moon, stay in sight.",
      "Glow can be a traveler",
      "and still be small and bright.",
      "",
      "Goodnight, new world.",
      "Goodnight, old trees.",
      "I brought my glow.",
      "I brought you with me.",
    ],
    placement: "Chapter 3 closer on the red dust.",
  },
];
